[package]
name = "actix-diesel-orm"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
diesel = { version = "2.2.4", features = ["postgres", "r2d2", "chrono"] }
actix-web = "4"
serde = { version = "1.0.214", features = ["derive"] }
dotenv = "0.15.0"
actix = "0.13.5"
